version: "3"

tasks:
  arxiv:
    cmds:
      - git archive --output=_build/arxiv-{{.DATE}}.tar.gz --add-file=paper/main.bbl HEAD:paper/
    vars:
      DATE:
        sh: date +%Y%m%d
  package-code:
    cmds:
      - mkdir -p _build/
      - |
        zip -r _build/code-{{.DATE}}.zip \
          scripts \
          results \
          data \
          src \
          test \
          Project.toml \
          Manifest.toml \
          flake.nix \
          flake.lock \
          README.md
    vars:
      DATE:
        sh: date +%Y%m%d
