version: "3"

tasks:
  arxiv:
    cmds:
      - mkdir -p _build/arxiv-temp
      - git archive HEAD:paper/ | tar -x -C _build/arxiv-temp
      - cp paper/main.bbl _build/arxiv-temp/
      - cp plots/* _build/arxiv-temp/
      - rm _build/arxiv-{{.DATE}}.tar.gz
      - cd _build/arxiv-temp && tar -czf ../arxiv-{{.DATE}}.tar.gz .
      - rm -rf _build/arxiv-temp
    vars:
      DATE:
        sh: date +%Y%m%d
  package-code:
    cmds:
      - mkdir -p _build/
      - |
        zip -r _build/code-{{.DATE}}.zip \
          scripts \
          results \
          data \
          src \
          test \
          Project.toml \
          Manifest.toml \
          flake.nix \
          flake.lock \
          README.md
    vars:
      DATE:
        sh: date +%Y%m%d
